var sysCities = {
		"fromcities": [
		 {"name":"Lima, PE", "id":"LIM"},
		 {"name":"Guayaquil, EC", "id":"GYE"},
		 {"name":"Quito, EC", "id":"UIO"}
           
		],
		"tocities": [
            
             {"name":"Asunci&oacute;n, PY","id": "ASU"},
            {"name":"Aruba, AW","id": "AUA"},
            {"name":"Barranquilla, CO", "id":"BAQ"},
            {"name":"Belo Horizonte, BR", "id":"CNF"},
            {"name":"Bogot&aacute;, CO", "id":"BOG"},
            {"name":"Boston, US", "id":"BOS"},
            {"name":"Brasilia, BR", "id":"BSB"},
			{"name":"Belize, BZ", "id":"BZE"},
            {"name":"Bucaramanga, CO", "id":"BGA"}, 
			{"name":"Buenos Aires, AR", "id":"EZE"},
            {"name":"Cali, CO", "id":"CLO"},
            {"name":"Campinas, BR", "id":"VCP"},
            {"name":"Canc&uacute;n, MX", "id":"CUN"},
            {"name":"Caracas, VE", "id":"CCS"},
            {"name":"Cartagena, CO", "id":"CTG"},
            {"name":"Chicago, US", "id":"ORD"},
			{"name":"Cordoba, AR", "id":"COR"},
            {"name":"C&uacute;cuta, CO", "id":"CUC"},
            {"name":"Curazao, AN", "id":"CUR"},
            {"name":"David, PA", "id":"DAV"},
            {"name":"Fort Lauderdale, US", "id":"FLL"},
            {"name":"Guadalajara, MX", "id":"GDL"},
			{"name":"Guayaquil, EC", "id":"GYE"},
            {"name":"Guatemala, GT", "id":"GUA"},
			{"name":"Georgetown, GY", "id":"GEO"},
            {"name":"Iquitos, PE", "id":"IQT"},
            {"name":"Kingston, JM", "id":"KIN"},
            {"name":"La Habana, CU", "id":"HAV"},
            {"name":"Liberia, CR", "id":"LIR"},
            {"name":"Lima, PE", "id":"LIM"},
			{"name":"Los Angeles, US", "id":"LOS"},
            {"name":"Managua, NI", "id":"MGA"},
            {"name":"Manaus, BR", "id":"MAO"},
            {"name":"Medell&iacute;­n, CO", "id":"MDE"},
            {"name":"M&eacute;xico - Ciudad, MX", "id":"MEX"},
            {"name":"Miami, US", "id":"MIA"},
            {"name":"Montego Bay, JM", "id":"MBJ"},
            {"name":"Monterrey, MX", "id":"MTY"},
            {"name":"Montevideo, UY", "id":"MVD"},
            {"name":"Montreal, CA", "id":"YUL"},
            {"name":"Nassau, BS", "id":"NAS"},
			{"name":"Nueva York, US", "id":"JFK"},
            {"name":"Nueva Orle&aacute;ns, US", "id":"MSY"},
            {"name":"Orlando, US", "id":"MCO"},
            {"name":"Panam&aacute;, PA", "id":"PTY"},
            {"name":"Pereira, CO", "id":"PEI"},
            {"name":"Porto Alegre, BR", "id":"POA"},
			{"name":"Puebla, MX", "id":"PBC"},
            {"name":"Puerto Espa&ntilde;a, TT", "id":"POS"},
			{"name":"Puerto Principe, HT", "id":"PAP"},
            {"name":"Punta Cana, DO", "id":"PUJ"},
			{"name":"Quito, EC", "id":"UIO"},
            {"name":"Recife, BR", "id":"REC"},
            {"name":"R&iacute;­o de Janeiro, BR", "id":"GIG"},
            {"name":"San Andr&eacute;s Isla, CO", "id":"ADZ"},
            {"name":"San Jos&eacute;, CR", "id":"SJO"},
            {"name":"San Juan, PR", "id":"SJU"},
            {"name":"San Pedro Sula, HN", "id":"SAP"},
            {"name":"San Salvador, SV", "id":"SAL"},
            {"name":"Santiago de Chile, CL", "id":"SCL"},
            {"name":"Santiago de los Caballeros, DO", "id":"STI"},
            {"name":"Santa Cruz, BO", "id":"VVI"},
            {"name":"Santa Clara, CU", "id":"SNU"},
            {"name":"Santo Domingo, DO", "id":"SDQ"},
		{"name":"San Francisco, US", "id":"SFO"},
            {"name":"Sao Paulo, BR", "id":"GRU"},
            {"name":"St Maarten, AN", "id":"SXM"},
            {"name":"Tampa, US", "id":"TPA"},
            {"name":"Tegucigalpa, HN", "id":"TGU"},
            {"name":"Toronto, CA", "id":"YYZ"},
            {"name":"Valencia, VE", "id":"VLN"},
			{"name":"Villahermosa, MX", "id":"VSA"},
            {"name":"Washington Dulles, US", "id":"IAD"}
		],

            tarifas: [
                  { 
                        origen: 'Guayaquil', 
                        destinos: [
                              { destino:'Caracas', antes:558, ahora:489 },
                              { destino:'Cancún', antes:1063, ahora:538 },
                              { destino:'La Habana', antes:868, ahora:476 },
                              { destino:'Los Ángeles', antes:942, ahora:573 },
                              { destino:'Maracaibo', antes:792, ahora:510 },
                              { destino:'México D.F.', antes:757, ahora:566 },
                              { destino:'Miami', antes:765, ahora:508 },
                              { destino:'Orlando', antes:837, ahora:514 },
                              { destino:'Panamá', antes:585, ahora:474 },
                              { destino:'Punta Cana', antes:1030, ahora:585 },
                              { destino:'Santo Domingo', antes:1022, ahora:582 },
                              { destino:'Santa Clara', antes:868, ahora:476 },
                              { destino:'Valencia', antes:748, ahora:500 }
                        ]  
                  },
                  {
                        origen: 'Lima',
                        destinos: [
                              { destino: 'San Andrés', antes:564, ahora:378 },
                              { destino: 'Aruba', antes:1116, ahora:690 },
                              { destino: 'Bogotá', antes:564, ahora:378 },
                              { destino: 'Curazao', antes:972, ahora:662 },
                              { destino: 'Fort Lauderdale', antes:910, ahora:589 },
                              { destino: 'La Habana', antes:710, ahora:498 },
                              { destino: 'Los Ángeles', antes:973, ahora:627 },
                              { destino: 'Manaos', antes:732, ahora:471 },
                              { destino: 'Montego Bay', antes:876, ahora:729 }
                        ]
                  },
                  {
                        origen: 'Quito',
                        destinos: [
                              { destino: 'Caracas', antes:598, ahora:491 },
                              { destino: 'Cancún', antes:931, ahora:534 },
                              { destino: 'La Habana', antes:557, ahora:398 },
                              { destino: 'Los Ángeles', antes:829, ahora:555 }
                        ]
                  }
            ]
	},

      departure_date = new Date(2016, 02 - 1, 05),
      return_date = new Date(2016, 06 - 1, 30);