var sysCities = {
		"fromcities": [
		 {"name":"Lima, PE", "id":"LIM"},
		 {"name":"Guayaquil, EC", "id":"GYE"},
		 {"name":"Quito, EC", "id":"UIO"}
           
		],
		"tocities": [
            
             {"name":"Asunci&oacute;n, PY","id": "ASU"},
            {"name":"Aruba, AW","id": "AUA"},
            {"name":"Barranquilla, CO", "id":"BAQ"},
            {"name":"Belo Horizonte, BR", "id":"CNF"},
            {"name":"Bogot&aacute;, CO", "id":"BOG"},
            {"name":"Boston, US", "id":"BOS"},
            {"name":"Brasilia, BR", "id":"BSB"},
			{"name":"Belize, BZ", "id":"BZE"},
            {"name":"Bucaramanga, CO", "id":"BGA"}, 
			{"name":"Buenos Aires, AR", "id":"EZE"},
            {"name":"Cali, CO", "id":"CLO"},
            {"name":"Campinas, BR", "id":"VCP"},
            {"name":"Canc&uacute;n, MX", "id":"CUN"},
            {"name":"Caracas, VE", "id":"CCS"},
            {"name":"Cartagena, CO", "id":"CTG"},
            {"name":"Chicago, US", "id":"ORD"},
			{"name":"Cordoba, AR", "id":"COR"},
            {"name":"C&uacute;cuta, CO", "id":"CUC"},
            {"name":"Curazao, AN", "id":"CUR"},
            {"name":"David, PA", "id":"DAV"},
            {"name":"Fort Lauderdale, US", "id":"FLL"},
            {"name":"Guadalajara, MX", "id":"GDL"},
			{"name":"Guayaquil, EC", "id":"GYE"},
            {"name":"Guatemala, GT", "id":"GUA"},
			{"name":"Georgetown, GY", "id":"GEO"},
            {"name":"Iquitos, PE", "id":"IQT"},
            {"name":"Kingston, JM", "id":"KIN"},
            {"name":"La Habana, CU", "id":"HAV"},
            {"name":"Liberia, CR", "id":"LIR"},
            {"name":"Lima, PE", "id":"LIM"},
			{"name":"Los Angeles, US", "id":"LOS"},
            {"name":"Managua, NI", "id":"MGA"},
            {"name":"Manaus, BR", "id":"MAO"},
            {"name":"Medell&iacute;­n, CO", "id":"MDE"},
            {"name":"M&eacute;xico - Ciudad, MX", "id":"MEX"},
            {"name":"Miami, US", "id":"MIA"},
            {"name":"Montego Bay, JM", "id":"MBJ"},
            {"name":"Monterrey, MX", "id":"MTY"},
            {"name":"Montevideo, UY", "id":"MVD"},
            {"name":"Montreal, CA", "id":"YUL"},
            {"name":"Nassau, BS", "id":"NAS"},
			{"name":"Nueva York, US", "id":"JFK"},
            {"name":"Nueva Orle&aacute;ns, US", "id":"MSY"},
            {"name":"Orlando, US", "id":"MCO"},
            {"name":"Panam&aacute;, PA", "id":"PTY"},
            {"name":"Pereira, CO", "id":"PEI"},
            {"name":"Porto Alegre, BR", "id":"POA"},
			{"name":"Puebla, MX", "id":"PBC"},
            {"name":"Puerto Espa&ntilde;a, TT", "id":"POS"},
			{"name":"Puerto Principe, HT", "id":"PAP"},
            {"name":"Punta Cana, DO", "id":"PUJ"},
			{"name":"Quito, EC", "id":"UIO"},
            {"name":"Recife, BR", "id":"REC"},
            {"name":"R&iacute;­o de Janeiro, BR", "id":"GIG"},
            {"name":"San Andr&eacute;s Isla, CO", "id":"ADZ"},
            {"name":"San Jos&eacute;, CR", "id":"SJO"},
            {"name":"San Juan, PR", "id":"SJU"},
            {"name":"San Pedro Sula, HN", "id":"SAP"},
            {"name":"San Salvador, SV", "id":"SAL"},
            {"name":"Santiago de Chile, CL", "id":"SCL"},
            {"name":"Santiago de los Caballeros, DO", "id":"STI"},
            {"name":"Santa Cruz, BO", "id":"VVI"},
            {"name":"Santa Clara, CU", "id":"SNU"},
            {"name":"Santo Domingo, DO", "id":"SDQ"},
			{"name":"San Francisco, US", "id":"SFO"},
            {"name":"Sao Paulo, BR", "id":"GRU"},
            {"name":"St Maarten, AN", "id":"SXM"},
            {"name":"Tampa, US", "id":"TPA"},
            {"name":"Tegucigalpa, HN", "id":"TGU"},
            {"name":"Toronto, CA", "id":"YYZ"},
            {"name":"Valencia, VE", "id":"VLN"},
			{"name":"Villahermosa, MX", "id":"VSA"},
            {"name":"Washington Dulles, US", "id":"IAD"}
   
            
			]
	},

      departure_date = new Date(2016, 02 - 1, 05),
      return_date = new Date(2016, 06 - 1, 30);